version: '3'

services:
  node-api:
    build:
      context: .
      dockerfile: Dockerfile
      target: development   
    ports:
      - 3000:3000
    depends_on:
      - mongodb
    env_file:
      - .env
    working_dir: /app/api-blood-donation
    volumes:
      - .:/app/api-blood-donation
    command: npm run dev

  mongodb:
    image: mongo
    volumes:
      - mongodb-data:/data/db

volumes:
  mongodb-data:
